### PR TITLE
fix: Improve mobile responsiveness and update links on amiusing.reque…

### LINKED ISSUE #3630: bug: Mobile responsiveness issues in amiusing.requestly.io and outdated links
### Describe your issue?

The [amiusing.requestly.io](amiusing.requestly.io) site is not fully responsive on mobile devices. Layout and usability issues occur when the page is on smaller screens. Additionally, several documentation links on the page still point to outdated URLs and need to be updated.

Links to Update -

- [Getting started](https://docs.requestly.com/general/getting-started/introduction)
- [Understanding Rule Operators](https://docs.requestly.com/general/http-rules/advanced-usage/source-conditions)
- [Modify HTTP(s) Headers](https://docs.requestly.com/general/http-rules/rule-types/modify-headers)
- [Modify Response Rule](https://docs.requestly.com/general/http-rules/rule-types/modify-response-body)
- [Inject Javascript or CSS to any website](https://docs.requestly.com/general/http-rules/rule-types/insert-scripts)
- [Coinditionally replace part of an URL String](https://docs.requestly.com/general/http-rules/rule-types/replace-strings)
- [Modify User Agent](https://docs.requestly.com/general/http-rules/rule-types/modify-user-agents)
- [Share your Rules](https://docs.requestly.com/general/http-rules/sharing)

### Repro steps

Open [amiusing.requestly.io](https://amiusing.requestly.io/) on a mobile device or use Chrome DevTools’ device toolbar. Observe layout issues and broken responsiveness.

### What Requestly tool were you using?

- [ ] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

any

### Requestly Version

any

### Error screenshot

Image

### PR DESCRIPTION
**Pull request by Somilg11**
closes: https://github.com/requestly/requestly/issues/3630
### Description

This PR addresses the mobile responsiveness issues and updates outdated documentation links on the `amiusing.requestly.io` site, making it more user-friendly and up-to-date.

---

### Related Issue

-   Closes #3630

---

### Changes Made

-   **Responsiveness:**
    -   Implemented CSS media queries to fix layout issues on smaller screens.
    -   Adjusted component styling to ensure proper alignment and prevent overflow on mobile devices.
-   **Link Updates:**
    -   Corrected the URLs for the following documentation links to point to their current locations:
        -   Getting started
        -   Understanding Rule Operators
        -   Modify HTTP(s) Headers
        -   Modify Response Rule
        -   Inject Javascript or CSS to any website
        -   Conditionally replace part of an URL String
        -   Modify User Agent
        -   Share your Rules

---

### How to Test

**1. Test Responsiveness:**
1.  Navigate to `amiusing.requestly.io` on your branch.
2.  Open your browser's developer tools and toggle the device toolbar to simulate mobile view.
3.  **Expected Result:** The page layout should be clean, readable, and fully functional on various mobile screen sizes.

**2. Test Links:**
1.  On the page, click each of the documentation links listed above.
2.  **Expected Result:** Each link should direct you to the correct, working documentation page.

### CODE REVIEW

**Comment by rohanmathur91** [comment]
@Somilg11 can you please share screenshot/demo video?

**Comment by Somilg11** [comment]
Yes @rohanmathur91 here is the mobile version screenshots
image
image

File: components/Yes.js [hunk 1]
```diff
@@ -33,56 +33,56 @@ export default function Yes() {
 
         <div className="options">
           <a
-            href="https://docs.requestly.com/general/getting-started--introduction"
+            href="https://docs.requestly.io/getting-started/installing-requestly"
```
Comment (rohanmathur91) [inline components/Yes.js]: Docs are on `docs.requestly.com` only, so need to update links.

**Review by rohanmathur91 — CHANGES_REQUESTED** [review]
Thanks for raising the PR @Somilg11 
Revert link changes, rest of it looks good to me.

**Review by rohanmathur91 — APPROVED** [review]
Looks good to me!

**Comment by Kanishkrawatt** [comment]
@Somilg11 Merging this now, thanks for contributing! 🚀
